name = "orbit"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

durable_objects.bindings = [
  { name = "ORBIT_DO", class_name = "OrbitRelay" }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "zane"
database_id = "ca5a5a6b-6822-4246-8fc2-136ed5b1c6a0"

[[migrations]]
tag = "v1"
new_classes = ["OrbitRelay"]
