name = "orbit"
main = "src/index.ts"
compatibility_date = "2025-01-01"

durable_objects.bindings = [
  { name = "ORBIT_DO", class_name = "OrbitRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["OrbitRelay"]
